### ISSUE TITLE
Make ol.Snap an interaction (ol.interaction.Snap) that modifies event coordinates

### ISSUE THREAD

**Issue by fperucic** [fperucic/ol3#1]
For interactions that are registered after an ol.interaction.Snap instance, the coordinates will be snapped to whatever the snap interaction wants to snap them to. This approach might require minor modifications to ol.MapBrowserEvent (setters for pixel and/or coordinate), but should get along without any modifications to ol.interaction.Draw and ol.interaction.Modify

**Comment by adube** [comment]
@fperucic, thanks for opening the issues.  I'll make pull requests for you to review.  I'll begin working on this today and let you know of my progress.

**Comment by adube** [comment]
This has been fixed and merged in the ol3 master repository.
